// src/hooks/useExport.ts

import { useState } from 'react';
import { toast } from 'sonner';
import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';

// Definisikan tipe data untuk kolom dan data
interface ExportColumn {
  header: string;
  dataKey: string;
}

// Definisikan interface ExportOptions
interface ExportOptions {
  filename: string;
  title: string;
  data: any[];
  columns: ExportColumn[];
}

export const useExport = () => {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPDF = async (options: ExportOptions) => {
    setIsExporting(true);
    try {
      // ✅ Buat instance jsPDF
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      // Header perusahaan
      doc.setFontSize(16);
      doc.text('Fintrack Affiliate', 14, 22);
      doc.setFontSize(12);
      doc.text('Affiliate Marketing Management System By FahmyID', 14, 32);
      doc.setFontSize(10);
      doc.text(`Tanggal: ${new Date().toLocaleDateString('id-ID')}`, 14, 42);

      // Garis pemisah
      doc.line(14, 48, 196, 48);

      // Judul laporan
      doc.setFontSize(14);
      doc.text(options.title, 14, 58);

      // ✅ Gunakan autoTable dengan API yang benar untuk v5.0.2
      autoTable(doc, {
        head: [options.columns.map(col => col.header)],
        body: options.data.map(row =>
          options.columns.map(col => row[col.dataKey] || '-')
        ),
        startY: 68,
        styles: {
          fontSize: 8,
          cellPadding: 3,
        },
        headStyles: {
          fillColor: [59, 130, 246], // Blue
          textColor: 255,
          fontStyle: 'bold',
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
        margin: { left: 14, right: 14 },
      });

      // Footer dengan nomor halaman
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.text(
          `Halaman ${i} dari ${pageCount}`,
          doc.internal.pageSize.getWidth() - 50,
          doc.internal.pageSize.getHeight() - 10
        );
        doc.text(
          'Generated by AffStudio Fahmy',
          14,
          doc.internal.pageSize.getHeight() - 10
        );
      }

      doc.save(`${options.filename}.pdf`);
      toast.success('File PDF berhasil diunduh!');
    } catch (error) {
      console.error('Export PDF error:', error);
      toast.error('Gagal mengekspor PDF: ' + (error instanceof Error ? error.message : 'Unknown error'));
    }
    setIsExporting(false);
  };

  const exportToCSV = (options: ExportOptions) => {
    setIsExporting(true);
    try {
      // Header CSV
      const headers = options.columns.map(col => col.header).join(',');

      // Data CSV
      const csvData = options.data.map(row =>
        options.columns.map(col => {
          const value = row[col.dataKey] || '';
          // Escape quotes dan wrap dengan quotes jika mengandung koma
          return typeof value === 'string' && value.includes(',')
            ? `"${value.replace(/"/g, '""')}"`
            : value;
        }).join(',')
      );

      // Gabungkan header dan data
      const csvContent = [headers, ...csvData].join('\n');

      // Buat blob dan download
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');

      if (link.download !== undefined) {
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', `${options.filename}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      }

      toast.success('File CSV berhasil diunduh!');
    } catch (error) {
      console.error('Export CSV error:', error);
      toast.error('Gagal mengekspor CSV');
    }
    setIsExporting(false);
  };

  const printData = (options: ExportOptions) => {
    try {
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast.error('Popup diblokir! Izinkan popup untuk mencetak.');
        return;
      }

      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${options.title}</title>
          <style>
            body { 
              font-family: Arial, sans-serif; 
              margin: 20px;
              color: #333;
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              border-bottom: 2px solid #3B82F6;
              padding-bottom: 20px;
            }
            .company { 
              font-size: 20px; 
              font-weight: bold; 
              color: #3B82F6;
            }
            .subtitle { 
              font-size: 14px; 
              color: #666; 
              margin: 5px 0;
            }
            .date { 
              font-size: 12px; 
              color: #666; 
            }
            .title { 
              font-size: 18px; 
              font-weight: bold; 
              margin: 20px 0; 
              text-align: center;
            }
            table { 
              width: 100%; 
              border-collapse: collapse; 
              margin: 20px 0;
            }
            th, td { 
              border: 1px solid #ddd; 
              padding: 8px; 
              text-align: left; 
            }
            th { 
              background-color: #3B82F6; 
              color: white; 
              font-weight: bold;
            }
            tr:nth-child(even) { 
              background-color: #f9f9f9; 
            }
            .footer {
              margin-top: 30px;
              text-align: center;
              font-size: 10px;
              color: #666;
            }
            @media print {
              body { margin: 0; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="company">PT FAHMYID</div>
            <div class="subtitle">Affiliate Marketing Management System</div>
            <div class="date">Tanggal: ${new Date().toLocaleDateString('id-ID')}</div>
          </div>

          <div class="title">${options.title}</div>

          <table>
            <thead>
              <tr>
                ${options.columns.map(col => `<th>${col.header}</th>`).join('')}
              </tr>
            </thead>
            <tbody>
              ${options.data.map(row => `
                <tr>
                  ${options.columns.map(col => `<td>${row[col.dataKey] || '-'}</td>`).join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            Generated by AffStudio Fahmy - ${new Date().toLocaleString('id-ID')}
          </div>

          <script>
            window.onload = function() {
              window.print();
              window.onafterprint = function() {
                window.close();
              };
            };
          </script>
        </body>
        </html>
      `;

      printWindow.document.write(htmlContent);
      printWindow.document.close();
    } catch (error) {
      console.error('Print error:', error);
      toast.error('Gagal mencetak data');
    }
  };

  return {
    exportToPDF,
    exportToCSV,
    printData,
    isExporting
  };
};