// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnwkbeigruouhsssfbym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZud2tiZWlncnVvdWhzc3NmYnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2OTQwNzMsImV4cCI6MjA3ODI3MDA3M30.NWaLn8LL9leWtcaINyMp_9cosnASv6G0mB7-J2zFWJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});